#server:
#  port: ${SERVER_PORT:8080}
#spring:
#  application.name: ${APPLICATION_NAME:spring-security-keycloak}
#  data:
#    mongodb:
#      host: api-database
#      port: 27017
#      database: rooms
#
#eureka:
#  instance:
#    instanceId: ${spring.application.name}:${random.uuid}
#
#keycloak:
#  enabled: ${KC_ENABLED:true}
#  auth-server-url: ${KC_AUTH_PROTOCOL:http}://${KC_AUTH_HOST:localhost:8484}/auth
#  proxy-url: ${KC_AUTH_PROXY_PROTOCOL:http}://${KC_AUTH_PROXY_HOST:localhost:8484}/auth
#  realm: bot
#  bearer-only: true
#  resource: ${KC_RESOURCE:ui}
#  ssl-required: NONE
#  use-resource-role-mappings: false
#  cors: true
#  expose-token: true